### PR TITLE
Make things easier to reproduce.

### PR DESCRIPTION
**Pull request by jgosmann**
I still have to go through a few things to ensure everything works properly, but you can already look at a first set of changes I did. You might not have to go through all the individual changes, but it might be useful to read the high-level overview below over as things to keep in mind for the next project.

* Put dependencies into `setup.py` to allow automatic installation.
* Don't rely on special projects, versions, or branches that might not  be accessible in the future:
  * Use pytry (which is pip installable from pytry) instead of    ctn_benchmarks.
  * Do not use the bleeding-edge branch of Nengo.
  These things required some minor changes to the model code.
* Ensure Python 3 compatibility.
  * Besides print statements this included replacing a bunch of    `map` and `filter` function calls with the corresponding list    comprehensions. Two reasons for that: In Python 3 those functions
    return generators instead of lists and would require casting to    work with the current code. Apparently, list comprehensions are    also more efficient and (I think) easier to understand.
* Update installation instructions to use `pip install -e .` (which  apparently should be used instead of `python setup.py develop` or  `install`; just found this out today)
* Fixed the doit output to match what is shown on a freshly checked out  repository.
* Changed the Github clone URL to https because this is easier to setup  for new Github users and works without a Github account.

### CODE REVIEW

**Comment by ikajic** [comment]
Just making sure before I merge, I assume you've tested the model with those changes and it runs ok?

**Comment by jgosmann** [comment]
Yes, I'm testing everything on a clean virtualenv with a freshly cloned repository. (It's the only way to ensure complete reproducibility.) Only exception are parts were the raw human data are required. (I'm not sure whether you gave them to me at all.)

**Comment by jgosmann** [comment]
Also, just to be clear: Do not merge yet, I will be going through a few more things today.

**Comment by jgosmann** [comment]
Does the `Neural_Filtering` notebook relate to anything in the paper?

**Comment by jgosmann** [comment]
The figshare project still lists the preliminary title, but I can't find a way to edit it. Can you have a look? Maybe only the creator can edit it. Here is the link: https://figshare.com/account/home#/projects/15504

**Comment by jgosmann** [comment]
Ok, I think everything is in a good state now except for the `Neural_Filtering` notebook. If it is not really needed in the repository, I would remove instead of trying to get it working properly.

**Comment by jgosmann** [comment]
Just remembered one more thing

**Comment by jgosmann** [comment]
Ok, all done except the notebook issue and figshare project title.

**Comment by ikajic** [comment]
> Ok, all done except the notebook issue and figshare project title.

I'll take care of those and merge. Thanks for your fixes.

**Pull request merged**
